name: Nightly Build

on:
  push:
    branches:
      - develop
  # schedule:
  #     - cron: '0 5 * * 1'

jobs:

  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 14days # Setting this to 0 will delete all artifacts

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:  
          ref: develop
      
      - name: Setup Toolchain Environment
        run: toolchains/linux/linux_install.sh

      - name: Build for Linux
        run: toolchains/linux/linux_compile.sh

      - name: Upload artifacts for Linux
        uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: bin/linux/linux-x64.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:  
          ref: develop

      - name: Build for macOS
        run: toolchains/macos/macos_compile.sh

      - name: Upload artifacts for macOS
        uses: actions/upload-artifact@v2
        with:
          name: darwin-x64
          path: bin/darwin/darwin-x64.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Build for Windows x64
        shell: pwsh
        run: .\toolchains\windows\scripts\compile.ps1 -a x64

      - name: Build for Windows x86
        shell: pwsh
        run: .\toolchains\windows\scripts\compile.ps1 -a x86

      - name: Upload artifacts for Windows x64
        uses: actions/upload-artifact@v2
        with:
          name: windows-x64
          path: .\bin\windows-x64\windows-x64.zip

      - name: Upload artifacts for Windows x86
        uses: actions/upload-artifact@v2
        with:
          name: windows-x86
          path: .\bin\windows-x86\windows-x86.zip

